import Link from "next/link";
import { IndicatorChart } from "./indicator-chart";
import { categoryLabels, faDate, frequencyLabels, relatedReasonLabel, safeExternalUrl, seasonalLabels, stateLabels } from "./labels";
import type { IndicatorDetailData } from "@/lib/indicators/types";

const fact = (label: string, value: React.ReactNode) => <><dt>{label}</dt><dd>{value ?? "—"}</dd></>;
export function IndicatorDetailPage({ data }: { data: IndicatorDetailData }) {
  const { detail, snapshot, chart, revisions, relatedSection, asOf } = data;
  const methodology = safeExternalUrl(detail.presentation.source_methodology_url), sourceUrl = safeExternalUrl(detail.source.reference_url);
  return <div className={`page-stack indicator-detail ${asOf ? "historical-mode" : "current-mode"}`}>
    <Link className="back-link" href="/fa/indicators">← بازگشت به کاتالوگ</Link>
    <header className="indicator-detail-header"><div><p className="eyebrow">{asOf ? "نمای تاریخیِ دانش" : "وضعیت فعلی"}</p><h1>{detail.presentation.display_name_fa}</h1><p className="latin-name" dir="ltr">{detail.canonical.name} · {detail.canonical.series_code}</p><p>{detail.presentation.description_fa}</p></div><div className={`snapshot-value metric-${snapshot.state}`}><span>{stateLabels[snapshot.state]}</span><strong dir="ltr">{snapshot.value ?? "—"}</strong><small>{snapshot.localized_unit_label}</small></div></header>
    {asOf && <aside className="historical-cutoff" role="note"><strong>مرز دانش تاریخی</strong><span dir="ltr">{asOf}</span><p>تصویر لحظه‌ای، نمودار و شواهد بازبینی فقط به اطلاعات شناخته‌شده تا این مرز UTC محدودند.</p></aside>}
    <form className="asof-switch" method="get" aria-label="انتخاب نمای زمانی"><Link aria-current={!asOf ? "page" : undefined} href={`/fa/indicators/${detail.canonical.series_id}`}>وضعیت فعلی</Link><label>مشاهدهٔ تاریخی تا پایان روز UTC<input type="date" name="date" defaultValue={asOf?.slice(0,10)} required /></label><button>نمایش تاریخی</button><p>تاریخ انتخابی به ساعت ۲۳:۵۹:۵۹٫۹۹۹ UTC همان روز تبدیل می‌شود؛ هیچ بازگشت پنهانی به دادهٔ فعلی رخ نمی‌دهد.</p></form>
    <section className="snapshot-panel"><header><h2>تصویر لحظه‌ای شاخص</h2><span className="metric-state">{stateLabels[snapshot.state]}</span></header><div className="snapshot-grid"><dl>{fact("مقدار دقیق", <span dir="ltr">{snapshot.value ?? "—"}</span>)}{fact("تغییر مطلق", <span dir="ltr">{snapshot.comparison.absolute_change ?? "—"}</span>)}{fact("تغییر درصدی", <span dir="ltr">{snapshot.comparison.percentage_change ?? "—"}</span>)}{fact("مقدار قبلی", <span dir="ltr">{snapshot.comparison.reference_value ?? "—"}</span>)}</dl><dl>{fact("تاریخ مشاهده", faDate(snapshot.observed_at))}{fact("انتشار منبع", faDate(snapshot.source_publication_timestamp))}{fact("مرز دانش", faDate(snapshot.knowledge_cutoff))}{fact("تازگی", snapshot.freshness.status === "current" ? "به‌روز" : snapshot.freshness.status === "stale" ? "کهنه" : "نامشخص")}</dl></div></section>
    {chart.status === "ready" ? <IndicatorChart points={chart.points} title={detail.presentation.display_name_fa} /> : <section className={chart.status === "error" ? "chart-error-state" : "chart-empty-state"} role={chart.status === "error" ? "alert" : "status"}><h2>{chart.status === "error" ? "تاریخچه در دسترس نیست" : "داده‌ای برای نمودار نیست"}</h2><p>مقدار مفقود به صفر تبدیل نشده است.</p></section>}
    <section className="research-grid"><article><h2>روش‌شناسی و فراداده</h2><p>{detail.presentation.methodology_summary_fa}</p><dl className="inline-facts">{fact("توضیح مرجع", detail.canonical.description)}{fact("دسته", categoryLabels[detail.canonical.category])}{fact("دوره", frequencyLabels[detail.canonical.frequency])}{fact("جغرافیا", detail.canonical.geography)}{fact("واحد", detail.canonical.unit)}{fact("ارز", detail.canonical.currency)}{fact("تعدیل فصلی", seasonalLabels[detail.presentation.seasonal_adjustment_status])}{fact("عملیاتی", detail.canonical.is_active ? "فعال" : "غیرفعال")}{fact("ویرایش", faDate(detail.curation.editorial_updated_at))}</dl>{methodology && <a href={methodology} target="_blank" rel="noopener noreferrer">روش‌شناسی منبع (پیوند خارجی)</a>}</article><article><h2>منبع</h2><h3>{detail.source.source_name}</h3><code>{detail.source.source_code}</code><p>{detail.source.description}</p>{sourceUrl && <a href={sourceUrl} target="_blank" rel="noopener noreferrer">مرجع منبع (پیوند خارجی)</a>}</article></section>
    <section className="evidence-section"><h2>شواهد بازبینی مقدار منتخب</h2>{revisions.length ? <div className="table-scroll"><table><thead><tr><th>توالی</th><th>زمان بازبینی</th><th>مقدار پیشین</th><th>مقدار بازبینی‌شده</th><th>دلیل</th></tr></thead><tbody>{revisions.map(r=><tr key={r.id}><td>{r.sequence}</td><td>{faDate(r.revision_timestamp)}</td><td dir="ltr">{r.previous_value ?? r.previous_status}</td><td dir="ltr">{r.revised_value ?? r.revised_status}</td><td>{r.reason}</td></tr>)}</tbody></table></div> : <p className="empty-note">برای مشاهدهٔ مؤثر انتخاب‌شده بازبینی ثبت نشده است.{asOf && " این نتیجه فقط اطلاعات موجود تا مرز دانش را نشان می‌دهد."}</p>}</section>
    <section className="evidence-section"><h2>شاخص‌های مشتق مرتبط</h2>{relatedSection.status === "historical_not_supported" ? <div className="historical-derived-notice" role="note"><strong>نمای تاریخی بدون نتایج مشتق</strong><p>شاخص‌های مشتق و Lineage در نمای تاریخی نمایش داده نمی‌شوند، زیرا قرارداد Historical As-of برای این بخش هنوز ارائه نشده است.</p></div> : relatedSection.status === "unavailable" ? <p className="empty-note">نتایج مشتق فعلی موقتاً در دسترس نیستند.</p> : <div className="related-grid">{relatedSection.related.items.map(item=><article key={item.relation_code}><header><div><h3>{item.relation_label_fa}</h3><p>{item.description_fa}</p></div><span className="metric-state">{stateLabels[item.state]}</span></header>{item.state === "available" ? <><strong className="derived-value" dir="ltr">{item.value}</strong><dl className="inline-facts">{fact("زمان مشاهده",faDate(item.observed_at))}{fact("تعریف",`${item.definition_code} / v${item.definition_version}`)}{fact("مرز محاسبه",faDate(item.calculation_cutoff))}{fact("تکمیل تحلیل",faDate(item.completed_at))}</dl>{item.run_id && item.observation_id && relatedSection.lineages[`${item.run_id}:${item.observation_id}`] && <details><summary>شواهد lineage</summary>{relatedSection.lineages[`${item.run_id}:${item.observation_id}`].items.map(line=><dl className="lineage" key={line.id}>{fact("ورودی",line.input_alias)}{fact("مشاهدهٔ منبع",line.source_observation_id)}{fact("نسخهٔ منبع",line.source_version_id)}{fact("بازبینی",line.source_revision_id)}{fact("زمان دانش",faDate(line.source_knowledge_timestamp))}</dl>)}</details>}</> : <><p className="empty-note">{stateLabels[item.state]} — {relatedReasonLabel(item.missing_reason)}</p>{item.missing_reason && <details><summary>جزئیات فنی</summary><code dir="ltr">{item.missing_reason}</code></details>}</>}</article>)}</div>}</section>
  </div>;
}
